// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package musicdiscs.domain;

import musicdiscs.domain.AlbumDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect AlbumIntegrationTest_Roo_IntegrationTest {
    
    declare @type: AlbumIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: AlbumIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: AlbumIntegrationTest: @Transactional;
    
    @Autowired
    private AlbumDataOnDemand AlbumIntegrationTest.dod;
    
    @Test
    public void AlbumIntegrationTest.testCountAlbums() {
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to initialize correctly", dod.getRandomAlbum());
        long count = musicdiscs.domain.Album.countAlbums();
        org.junit.Assert.assertTrue("Counter for 'Album' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void AlbumIntegrationTest.testFindAlbum() {
        musicdiscs.domain.Album obj = dod.getRandomAlbum();
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to provide an identifier", id);
        obj = musicdiscs.domain.Album.findAlbum(id);
        org.junit.Assert.assertNotNull("Find method for 'Album' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Album' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void AlbumIntegrationTest.testFindAllAlbums() {
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to initialize correctly", dod.getRandomAlbum());
        long count = musicdiscs.domain.Album.countAlbums();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Album', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<musicdiscs.domain.Album> result = musicdiscs.domain.Album.findAllAlbums();
        org.junit.Assert.assertNotNull("Find all method for 'Album' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Album' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void AlbumIntegrationTest.testFindAlbumEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to initialize correctly", dod.getRandomAlbum());
        long count = musicdiscs.domain.Album.countAlbums();
        if (count > 20) count = 20;
        java.util.List<musicdiscs.domain.Album> result = musicdiscs.domain.Album.findAlbumEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Album' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Album' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void AlbumIntegrationTest.testFlush() {
        musicdiscs.domain.Album obj = dod.getRandomAlbum();
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to provide an identifier", id);
        obj = musicdiscs.domain.Album.findAlbum(id);
        org.junit.Assert.assertNotNull("Find method for 'Album' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyAlbum(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Album' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AlbumIntegrationTest.testMerge() {
        musicdiscs.domain.Album obj = dod.getRandomAlbum();
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to provide an identifier", id);
        obj = musicdiscs.domain.Album.findAlbum(id);
        boolean modified =  dod.modifyAlbum(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        musicdiscs.domain.Album merged = (musicdiscs.domain.Album) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Album' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void AlbumIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to initialize correctly", dod.getRandomAlbum());
        musicdiscs.domain.Album obj = dod.getNewTransientAlbum(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Album' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Album' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void AlbumIntegrationTest.testRemove() {
        musicdiscs.domain.Album obj = dod.getRandomAlbum();
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Album' failed to provide an identifier", id);
        obj = musicdiscs.domain.Album.findAlbum(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Album' with identifier '" + id + "'", musicdiscs.domain.Album.findAlbum(id));
    }
    
}
