// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package musicdiscs.domain;

import musicdiscs.domain.ArtistDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect ArtistIntegrationTest_Roo_IntegrationTest {
    
    declare @type: ArtistIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: ArtistIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: ArtistIntegrationTest: @Transactional;
    
    @Autowired
    private ArtistDataOnDemand ArtistIntegrationTest.dod;
    
    @Test
    public void ArtistIntegrationTest.testCountArtists() {
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to initialize correctly", dod.getRandomArtist());
        long count = musicdiscs.domain.Artist.countArtists();
        org.junit.Assert.assertTrue("Counter for 'Artist' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void ArtistIntegrationTest.testFindArtist() {
        musicdiscs.domain.Artist obj = dod.getRandomArtist();
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to provide an identifier", id);
        obj = musicdiscs.domain.Artist.findArtist(id);
        org.junit.Assert.assertNotNull("Find method for 'Artist' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Artist' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void ArtistIntegrationTest.testFindAllArtists() {
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to initialize correctly", dod.getRandomArtist());
        long count = musicdiscs.domain.Artist.countArtists();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Artist', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<musicdiscs.domain.Artist> result = musicdiscs.domain.Artist.findAllArtists();
        org.junit.Assert.assertNotNull("Find all method for 'Artist' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Artist' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void ArtistIntegrationTest.testFindArtistEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to initialize correctly", dod.getRandomArtist());
        long count = musicdiscs.domain.Artist.countArtists();
        if (count > 20) count = 20;
        java.util.List<musicdiscs.domain.Artist> result = musicdiscs.domain.Artist.findArtistEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Artist' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Artist' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void ArtistIntegrationTest.testFlush() {
        musicdiscs.domain.Artist obj = dod.getRandomArtist();
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to provide an identifier", id);
        obj = musicdiscs.domain.Artist.findArtist(id);
        org.junit.Assert.assertNotNull("Find method for 'Artist' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyArtist(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Artist' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ArtistIntegrationTest.testMerge() {
        musicdiscs.domain.Artist obj = dod.getRandomArtist();
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to provide an identifier", id);
        obj = musicdiscs.domain.Artist.findArtist(id);
        boolean modified =  dod.modifyArtist(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        musicdiscs.domain.Artist merged = (musicdiscs.domain.Artist) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Artist' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void ArtistIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to initialize correctly", dod.getRandomArtist());
        musicdiscs.domain.Artist obj = dod.getNewTransientArtist(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Artist' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Artist' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void ArtistIntegrationTest.testRemove() {
        musicdiscs.domain.Artist obj = dod.getRandomArtist();
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Artist' failed to provide an identifier", id);
        obj = musicdiscs.domain.Artist.findArtist(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Artist' with identifier '" + id + "'", musicdiscs.domain.Artist.findArtist(id));
    }
    
}
